### ISSUE TITLE
if there are hacks found on hShop, Add WarioWare - D.I.Y. DS saves containing the Wii content & EU Themesoft onto 3hs too (totally clean and no cheat infections)?.

### ISSUE THREAD

**Issue by McVirginleth0** [MyPasswordIsWeak/3hs#6]
is it possible to get these onto hShop? and downloaded for TwilightMenu++ [DLC & Wii saves for WarioWare - D.I.Y. DS.zip](https://github.com/MyPasswordIsWeak/3hs/files/10952011/DLC.Wii.saves.for.WarioWare.-.D.I.Y.DS.zip)
also the mistakes from WarioWare D.I.Y. clean no cheats fresh micros saves - quick port from the GameFaqs D.I.Y. Showcase saves (Rev 1).zip from a closed issue from Universal-Updater (only the EU Themesoft and Wii saves got fixed in this upload, if you inject a mio into the first slot of DIY DS before starting the data it automatically deletes it after that forced making "WarioQuest", so the last slot is moved to the fifth slot instead, didn't fix the rest tho) (also there is a eu themesoft micro "minigolf" that was previously exclusive to that european GameFaqs D.I.Y. Showcase save, that's pretty much missing from DoujinSoft, dumped that mio file from that eu only save, and waiting for the website to notice. it's also in the EU THEME GAMES 15-17 and the ported from the Wii's european save to the USA DS version. "monochrome (13) super hero (14) and adventure (15)")

(BTW didn't extract the german and italian versions of the D.I.Y. showcase micros because didn't want to risk a US regional Wii brick from changing the region)

**Comment by MyPasswordIsWeak** [comment]
This repository contains the source code for the 3hs application, that is the hShop client, not including the contents, which are stored on the server. This repository is also not meant to be contributed to, as you can read in the README file. This issue is one that should be taken to the Discord server linked to on the hShop website.

**Comment by McVirginleth0** [comment]
could you delete this issue, mostly pretend it never happened as this topic is now outdated, but still download and send this clean without any cheats DLC/Wii saves for DS to the discord of hShop (and archiving it) (especially now the delete option for me on this issue got removed from here)
[DLC.Wii.saves.for.WarioWare.-.D.I.Y.DS.zip](https://github.com/MyPasswordIsWeak/3hs/files/10952314/DLC.Wii.saves.for.WarioWare.-.D.I.Y.DS.zip)

**Comment by McVirginleth0** [comment]
delete this issue already, the files here are good but the writing in this issue pretty much sucks and looks like hot garbage, get rid of this issue but still keep the files.
