### ISSUE TITLE
delete both this issue & issue #6, option to delete it myself was already removed even before deleting the account.

### ISSUE THREAD

**Issue by ghost** [MyPasswordIsWeak/3hs#7]
https://github.com/MyPasswordIsWeak/3hs/issues/6
[DLC.Wii.saves.for.WarioWare.-.D.I.Y.DS.zip](https://github.com/MyPasswordIsWeak/3hs/files/10952590/DLC.Wii.saves.for.WarioWare.-.D.I.Y.DS.zip)

**Comment by sylvainfesucks0** [comment]
get these save uploaded to hshop but still delete this issue
